### ISSUE TITLE
Elassandra multi data center replication

### ISSUE THREAD

**Issue by erangaeb** [strapdata/elassandra#283]
I have setup multi data center elassandra cluster. Created keyspace with `RF=2` and a table `connects`
```
CREATE KEYSPACE IF NOT EXISTS mystiko
WITH replication = {
    'class':'NetworkTopologyStrategy',
     'DC1':'2',
     'DC2':'2'
};

CREATE TABLE IF NOT EXISTS mystiko.connects (
    account TEXT,
    salt TEXT,
    signature TEXT,
    verified BOOLEAN,
    timestamp TIMESTAMP,
    PRIMARY KEY(account)
);
```

Then created elastic index with the `connects` table from DC1 node. 

```
curl -XPUT "http://172.31.20.177:9200/connects" -d '{
    "settings":{
          "keyspace": "mystiko"
     },
    "mappings": {
        "connects" : {
             "discover" : ".*"
         }
     }
}
'
```

When I'm looking at the elastic index replications, in one data center it gives `3` and other data center it gives `1`. Is this the known behavior of elassandra?

DC1
```
"settings" : {
     "index" : {
          "keyspace" : "mystiko",
           "number_of_shards" : "1",
           "provided_name" : "connects",
           "creation_date" : "1556749099033",
           "number_of_replicas" : "3",
           "uuid" : "GUEyLFy6S_m7k39hPqD7lg",
           "version" : {
               "created" : "5050099"
           }
      }
 },
```

DC2
```
"settings" : {
    "index" : {
          "keyspace" : "mystiko",
          "number_of_shards" : "1",
          "provided_name" : "connects",
          "creation_date" : "1556749099033",
          "number_of_replicas" : "1",
          "uuid" : "GUEyLFy6S_m7k39hPqD7lg",
          "version" : {
               "created" : "5050099"
           }
     }
}
```

Is there any way to have the same elastic replication on each data center?

**Comment by vroyer** [comment]
In Elassandra, data replication is driven by Cassandra according to the keyspace replication map, number_of_replicas is just an information to keep the same elasticsearch behaviour. 
(number_of_replicas = RF -1 in each datacenter).

There is a bug in multi-datacenter configuration, on the datacenter where the index is created, the replication factor used to compute the number_of_replicas is the global replication factor, here 4 (and not the local one, here 2). 

This is fixed for the next release.

**Comment by erangaeb** [comment]
Ok, that means in a multidata center environment elastic local replications not working in one data center? We plan to deploy a production elassandra cluster now, is there any concern with deploying with this bug? 

Thank you.

**Comment by DBarthe** [comment]
Hello !
This is not a problem because the replication is managed at the cassandra
layer.
The "number_of_replicas" returned by elastic is just aesthetic and it
doesn't control what's happening behind.

**Comment by erangaeb** [comment]
Hello,

Thank you for the information. We will deploy in prod now. When next release available we can update it later.

**Comment by pramodShehan5** [comment]
Hello,

We updated elassandra version including your fix. But this issue still is in here.

I  have three node cluster with three node disaster recovery cluster,

DC1 - 
    

1. node1
2. node2
3. node3

DC2 (DR) - 
   

1. node1
2.    node2
3.    node3


* replication_strategy - DC1 : 3 , DC2 : 3

Then created elastic index with the connects table from DC1 node. 

When I'm looking at the elastic index replications, I logged into every node and use these commands,

- **curl -X GET 'localhost:9200/<elasticsearch index>'**

- **curl -X GET 'localhost:9200/_cat/indices?v'**

its results were look like this,

DC1 - node1

```
"settings" : {
      "index" : {
        "keyspace" : "test_keyspace",
        "number_of_shards" : "3",
        "provided_name" : "test",
        "creation_date" : "1557757611830",
        "number_of_replicas" : "2",
        "uuid" : "N39kg_x4QZCGP7BA2M7OsQ",
        "version" : {
          "created" : "6020399"
        }
      }
    }

```
```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   3   2          0            0       624b           624b

```


DC1 - node2

```
"settings" : {
      "index" : {
        "keyspace" : "test_keyspace",
        "creation_date" : "1557757611830",
        "uuid" : "N39kg_x4QZCGP7BA2M7OsQ",
        "version" : {
          "created" : "6020399"
        },
        "provided_name" : "test"
      }
    }

```
```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b

```

DC1 - node3

```
"settings" : {
      "index" : {
        "keyspace" : "test_keyspace",
        "creation_date" : "1557757611830",
        "uuid" : "N39kg_x4QZCGP7BA2M7OsQ",
        "version" : {
          "created" : "6020399"
        },
        "provided_name" : "test"
      }
    }
```

```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b
```


DC2 (disaster recovery) - node1

```
"settings" : {
      "index" : {
        "keyspace" : "test_keyspace",
        "creation_date" : "1557757611830",
        "uuid" : "N39kg_x4QZCGP7BA2M7OsQ",
        "version" : {
          "created" : "6020399"
        },
        "provided_name" : "test"
      }
    }

```
```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b

```

DC2 (disaster recovery) - node2

```
"settings" : {
      "index" : {
        "keyspace" : "test_keyspace",
        "creation_date" : "1557757611830",
        "uuid" : "N39kg_x4QZCGP7BA2M7OsQ",
        "version" : {
          "created" : "6020399"
        },
        "provided_name" : "test"
      }
    }

```
```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b

```

DC2 (disaster recovery) - node3

```
"settings" : {
      "index" : {
        "keyspace" : "test_keyspace",
        "creation_date" : "1557757611830",
        "uuid" : "N39kg_x4QZCGP7BA2M7OsQ",
        "version" : {
          "created" : "6020399"
        },
        "provided_name" : "test"
      }
    }

```
```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b
```

**Comment by vroyer** [comment]
The number_of_shards and number_of_replica are just an information in elassandra, it's not a settings, it's just informational. These are computed from the underlying keyspace replication map, and now, the number_of_replica is correct (2 = RF -1, and not 6 as you had before the fix). The issue is now that this information is only computed on the last coordinator node where you probably created the index (node 1 DC1).  If you close/open the index on another node, that node will have number_of_shards and number_of_replica computed, but not the others. Could you confirm that ?

**Comment by pramodShehan5** [comment]
I closed elasticsearch index by using **curl -X POST "localhost:9200/test/_close"** in DC1/node2.

Before closing index,

**DC1 - node1**

```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   3   2          0            0       624b           624b
```

**DC1 - node2**

```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b
```

After closing and open index,

**DC1 - node1**

```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b

```
**DC1 - node2**

```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test           N39kg_x4QZCGP7BA2M7OsQ   1   0          0            0       624b           624b


```
it is not displayed number of replicas. Is there any reason for that?

**Comment by pramodShehan5** [comment]
Hi,

Is there any update regarding this ticket ?

**Comment by vroyer** [comment]
Close and open your index please, then look at index settings in DC1 and DC2. 
Thanks.

**Comment by pramodShehan5** [comment]
I did it and its replications and primary shards are very strange.

I have commented it previously .

**Comment by vroyer** [comment]
Closing inactive ticket
